### PR TITLE
Fix Healthy Scout & Peak Form perks, implementation via model wrapping

### PR DESCRIPTION
**Pull request by Tyler-IN**
Fixes https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/30

### CODE REVIEW

**Comment by Tyler-IN** [comment]
Yeah if another mod changes out the model it doesn't apply.

Might need to add a fallback patch to handle that scenario, but if a mod is replacing the model, it might not even want to take the default behavior into account...

I also don't know if this even works yet, haven't tested in game.

**Comment by Skau** [comment]
Well, I belive they definitely still want the perk fixes even with custom models. That's what I'm getting at. Swapping out a model breaking a perk fix doesn't feel right.

**Comment by tynakuh** [comment]
I like the approach, but agreed, I'd imagine lots of mods will be going down the custom models approach, which means they're losing out on the perk fixes themselves if they haven't implemented them. I think i'd prefer not checking if the models a custom one myself but I can see arguments for and against that.

Is it possible to add a check for if TaleWorlds fixes this, that way when they put a fix out (assuming they fix it in the default model, seems sensible to me though) we aren't doubling perk effects.

**Comment by Tyler-IN** [comment]
This needs an IL hash check

**Comment by Tyler-IN** [comment]
Prefer #60

**Pull request closed without merging**
