### PR TITLE
Update SubModule.xml

### PR DESCRIPTION
**Pull request by data54**
Added DependedModule for the main game files so it doesn't load before the main game files or randomize load order of the other mods

### CODE REVIEW

**Comment by Tyler-IN** [comment]
Is this the same as https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/19 ?

**Comment by data54** [comment]
Looks like it

**Comment by data54** [comment]
Might still be worth doing even if your mod doesn't require it, looks like not having it can potentially break existing mods that do.
With it:
image
Without:
image
Character Trainer DependedModules node:
image

**Comment by Tyler-IN** [comment]
> it can potentially break existing mods that do.

Can you provide an example of it breaking an existing mod?

**Comment by Grandnovus** [comment]
You saw the same thing I did regarding the mod load list (I was the one that opened #19 ).

However using the fixed launcher mod (https://www.nexusmods.com/mountandblade2bannerlord/mods/205) sorted out that issue.

image

I'm not 100% sure if I launched the game using the set-up above but I don't believe it actually had any negative effects.

Tyler walked me through how the launcher loads mods and in what order after I posted #19 and it shouldn't make a difference 

> [1:39 PM] ̑🅠: so ... it basically just goes by depth then file name
> [1:40 PM] ̑🅠: once the submodules are loaded, the dependencies matter
> [1:40 PM] ̑🅠: native comes first, then anything with no dependencies, then anything with dependencies (incl. official modules)

**Comment by Tyler-IN** [comment]
Linking to #53

**Comment by data54** [comment]
> > it can potentially break existing mods that do.
> 
> Can you provide an example of it breaking an existing mod?
> 
> e.g. Does CharacterTrainer actually break, or does the sort order just look wrong?

It doesn't break character trainer but it seems a bit random on what mod ends up ahead of the main game files, guessing there's a null ref or something in the launcher itself that causes it to break if it comes across a mod that doesn't have it in the xml.  When I originally started adding mods to the game the bannerlord tweaks mod was loading before its dependencies which did break the game, only thing that fixed it was making sure every mod I had contained the DependedModules.

**Pull request closed without merging**
