### PR TITLE
Make project easier to build for new people

### PR DESCRIPTION
**Pull request by iPherian**
Updates the readme to tell people the intended place for the repo. (the Modules dir).

Also reduce repetition in \*.csproj files by moving reference etc paths to project properties like 'MnB2BannerlordBinDir' when possible. While it works without this, someday someone might want to build with Bannerlord or the repo somewhere else and this would help them.

### CODE REVIEW

**Comment by fnzr** [comment]
I think making the project run out of the box is a great goal.
I think it's worth adding to the readme that the project expects it to be located under `Mount & Blade II Bannerlord\Modules` folder.
In the csproj file, we can leave the BinDir as is and change the launcher to variable to
`<MnB2BannerlordLauncher>./TaleWorlds.MountAndBlade.Launcher.exe</MnB2BannerlordLauncher>`
This way, in the default launch settings, instead of a new variable `$(MnB2BannerlordDir)`, we can use `$(MnB2BannerlordBinDir)` and the project should build and launch correctly.

**Comment by iPherian** [comment]
Ohhhh you're supposed to put it in the Modules folder. That would've been a lot easier.

**Comment by Tyler-IN** [comment]
There's also a `LocateSteamApp` project in there that can be wired up, but Facepunch.Steamworks is a little buggy inside MSBuild so I included custom-built binaries and a facade for dynamic linkage.
There's a usage of it over [here](https://github.com/ahmed007boss/Bannerlord-ModsSettings/blob/support-multiple-developers/src/Directory.Build.props);

```cs
<UsingTask TaskName="LocateSteamAppTask" AssemblyFile="$(MSBuildThisFileDirectory)\..\tools\LocateSteamApp.dll"/>
  <Target Name="LocateBannerlord" BeforeTargets="Build;Compile;CoreCompile;BeforeResolveReferences;ResolveAssemblyReferences">   
    <LocateSteamAppTask AppId="261550">
      <Output TaskParameter="Path" PropertyName="BannerlordDir"/>
    </LocateSteamAppTask>
...
```

But for some reason @ahmed007boss encounters an exception when it runs.

**Comment by iPherian** [comment]
And then nobody would ever have to configure it. That sounds pretty cool.

Shall I do the easy part? Pushed commit.

**Comment by Tyler-IN** [comment]
Does it work?

**Comment by fnzr** [comment]
Doesnt'work out of the box for me, it's necessary to update `Properties\launchSettings.json`, `workingDirectory` key to `$(MnB2BannerlordBinDir)` and *csproj file `<MnB2BannerlordLauncher>./TaleWorlds.MountAndBlade.Launcher.exe</MnB2BannerlordLauncher>` for the launcher to show up.

**Comment by iPherian** [comment]
@fnzr does that work better?

**Pull request merged**
