### PR TITLE
Sync master to dev after PRs targeting master are done before release (No.2)

### PR DESCRIPTION
**Pull request by Tyler-IN**

### CODE REVIEW

**Comment by Tyler-IN** [comment]
Idk if we need to add a dependency on StoryMode, do we have any direct refs, or are they all indirectly referenced? (e.g. `Type.GetType(assemblyQualifiedTypeName)`)

**Comment by iPherian** [comment]
> I don't know if we need to add a dependency on StoryMode, do we have any direct refs, or are they all indirectly referenced? (e.g. `Type.GetType(assemblyQualifiedTypeName)`)
> 
> And if we do, we need to add it to SubModule.xml

It's one of the refs in the [*.csproj](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/blob/dev/src/CommunityPatch/CommunityPatch.csproj#L42) file and there's a `using StoryMode` statement in an existing file.

I think adding it to SubModule.xml should be a seperate PR tho.

**Comment by iPherian** [comment]
> I don't know if we need to add a dependency on StoryMode, do we have any direct refs, or are they all indirectly referenced? (e.g. `Type.GetType(assemblyQualifiedTypeName)`)
> 
> And if we do, we need to add it to SubModule.xml

@Tyler-IN It's one of the refs in the [*.csproj](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/blob/dev/src/CommunityPatch/CommunityPatch.csproj#L42) file and there's a [`using StoryMode`](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/blob/dev/src/CommunityPatch/Patches/EarlyStoryVisibleTimeoutPatch.cs#L5) statement in an existing file.

I think adding it to SubModule.xml should be a seperate PR tho.

**Comment by iPherian** [comment]
[PR](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/212) for StoryMode dependency

**Comment by iPherian** [comment]
Reference of the commits in this PR already existing on dev:

[458e7d8 - Fix user not being told that FirstPhase story quests fail in 10 years](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/commit/458e7d828d58892c55491f99a682375c4a7d9a22)
[1791a13 - move to IPatch class EarlyStoryVisibleTimeoutPatch](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/commit/1791a138a29b8cb8b8e879fc4a93f76b7e9c0e21)

**Comment by Tyler-IN** [comment]
Yeah I read from the issue, I will drop them instead of merge them. This is to track any more diffs before we do the next release though. They should be gone in a sec.

**Comment by iPherian** [comment]
Excellent!

**Pull request closed without merging**
