### PR TITLE
Fix Mounted Archer, Bow Expert, Crossbow Cavalry, and Crossbow Expert perks.

### PR DESCRIPTION
**Pull request by ajseavey**
Addresses #10 by overriding flags and usability on the hero adding said perks or on loading while the hero has said perks. Based on my solution from https://www.nexusmods.com/mountandblade2bannerlord/mods/215.

### CODE REVIEW

**Comment by Skau** [comment]
Nice! You should update the readme too with the fixes.

**Comment by ajseavey** [comment]
Done and done

**Comment by Tyler-IN** [comment]
The patches look ok at first glance...
However, the IsApplicable bits just check to see if it's a Campaign and there's a Player Troop with a Hero? The implementation should check to see if the patch is "applicable" in the sense that it isn't already fixed or patched by another mod.

Looking at the patches a bit more, what's the deal with the serialization stuff and checking if it's the player hero?

**Comment by ajseavey** [comment]
The `AddNonSerializedListener` is just adding an event listener on the `PerkOpened` (Perk Added) event. Also I'm not too savvy on when that triggers, but it may trigger when you do it for a companion, and since as far as I can tell the changes I'm making are global for the ItemObject I'm changing, at least for now, it seems wiser to restrict it to when the player character gets the perk.

Also, sorry about the `IsApplicable` stuff. I wasn't entirely sure of the intended purpose of that was. I'll fix those conditions soon. I may also look into method patching to maybe change it for only characters with the perk.

**Comment by Tyler-IN** [comment]
So would this affect other game characters?

E.g. your hero can equip bows on horseback, but then suddenly so can the opposing heroes?

**Comment by ajseavey** [comment]
I don't know if the opposing heroes would do so, but as far as I can tell this would make it possible for you to equip you companions with a long bow and a horse and they should be able to use it if you have the perk, as far as I can tell. I'm looking for ways to restrict that based on the character but that also is making me wonder if any regular cavalry units use long bow or crossbow.

**Comment by ajseavey** [comment]
So looking at `Agent.TryToWieldWeaponInSlot` it makes a call to an interface full of `EngineMethod` annotated methods which I'm not sure if those are super internal or what. It's a lead to look into but I'm not sure how big of a rabbithole it'll be.

**Comment by Skau** [comment]
There's also `Agent.EquipWeaponWithNewEntity` where you get the weapon in as an parameter directly. Instead of globally setting the values on all weapons you could just do it on the currently equipped weapon, and "turn it off" again when it's dropped or removed. This would make it so only the hero with the perk will have the effect. By using `Agent` you would have to get the corresponding `Hero` to see the perks. Just my two cents, might be better ways.

**Comment by ajseavey** [comment]
Ideally I could find the logic that uses the flags I'm changing and overwrite that logic but it seems like that might be buried pretty deep.

**Comment by ajseavey** [comment]
It does absolutely seem like `Agent.TryToWieldWeaponInSlot` is what I want, but since it makes a call off to that interface I have yet to figure out what I need to modify to make it do what I want.

**Comment by Tyler-IN** [comment]
I don't see any more changes here yet.

Can you implement IsApplicable like I described above?

I'm going to investigate TryToWieldWeaponInSlot and give some feedback here soon.

**Comment by ajseavey** [comment]
Sorry have been at work.  Will do so when I'm done for the day.

**Comment by Tyler-IN** [comment]
See if you can join us on Discord and we can add you as a contributor to the project.

**Comment by ajseavey** [comment]
I'm on the Mount and Blade discord. Svered#1526

**Comment by Tyler-IN** [comment]
Update on this;

We discussed the craziness of how switching weapons and reloading are done.

Native code and callbacks come into play here.
I'd like to try to have this work for all heroes with the right perks, and none of the other parties.
If the AI doesn't ever use crossbows and longbows on horseback, then we can can go with this, but it might screw with other mods or have some strange edge cases.

**Comment by ajseavey** [comment]
I am working on rewriting it to be more generally correct and hopefully that works. If not this can be a fallback implementation.

**Comment by Tyler-IN** [comment]
Just letting the community know, @ajseavey is still working on this issue and has made good progress identifying a way to fix this directly and splitting up the issues into separate patches.

The major hurdle faced with these is that they call into native code in Game.dll.

**Comment by ajseavey** [comment]
Closing since I've since redesigned how I'm doing this and have seperate PRs for those patches.

**Pull request closed without merging**
