### PR TITLE
Add patches to fix movement bonuses and the snow debuff

### PR DESCRIPTION
**Pull request by wonkotron**
Merging functionality from Cultural Feat Fixes
https://github.com/wonkotron/CulturalFeatFixes

- Battanian Forest Agility
- Khuzait Cavalry Agility
- Sturgian Snow Agility
- Snow movement debuff based on atmospheric data at party location

### CODE REVIEW

**Comment by iPherian** [comment]
Offhand, I think it's not needed to merge in master for a PR. All of the stuff on it already got rebased onto dev branch anyway, and as you can see from github's warning, it creates certain conflicts.

I'm sure if they want to merge dev into master they could do it, but I think they would know whether that's a good idea or not.

**Comment by Tyler-IN** [comment]
This needs to be manually rebased on dev, yeah.

**Comment by iPherian** [comment]
My suggestion is to change your PR branch to remove those first two commits from me. Your stuff doesn't depend on them, they're already in the branch your PR is going into, and while git doesn't seem to have a warning anymore, you never know it might cause weirdness in the future.

(The commits to remove are [`b127c99 - Fix user not being told that FirstPhase story quests fail in 10 years`](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/201/commits/b127c9927498b29d0c6e887b5c838294f7466f14) and [`02d0930 - move to IPatch class EarlyStoryVisibleTimeoutPatch`](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/201/commits/02d09308dadf49a2a0bd11702ab6fe337395742e))

**Comment by wonkotron** [comment]
> My suggestion is to change your PR branch to remove those first two commits from me. Your stuff doesn't depend on them, they're already in the branch your PR is going into, and while git doesn't seem to have a warning anymore, you never know it might cause weirdness in the future.
> 
> (The commits to remove are [`b127c99 - Fix user not being told that FirstPhase story quests fail in 10 years`](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/201/commits/b127c9927498b29d0c6e887b5c838294f7466f14) and [`02d0930 - move to IPatch class EarlyStoryVisibleTimeoutPatch`](https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/pull/201/commits/02d09308dadf49a2a0bd11702ab6fe337395742e))

Dropped commits in rebase

**Comment by iPherian** [comment]
> Dropped commits in rebase

Thanks!

**Pull request merged**
